# Docker Compose file for CS4480 PA3 Part 1 Full Topology
# Using 10.0.x.0/24 subnets
# IP Pattern: HA/HB=.3, R1/R3=.4, R2/R4=.5 (Avoids .1)

version: '3.8' # Specifies the version of the Docker Compose file format

services:
  ha: # Host A
    build: . # Use the Dockerfile in the current directory
    hostname: hosta
    stdin_open: true # Keep STDIN open even if not attached (-i)
    tty: true        # Allocate a pseudo-TTY (-t)
    cap_add:
      - ALL        # Grant all capabilities (needed for network config)
    privileged: true # Run container in privileged mode (needed for network config)
    networks:
      net_ha_r1:
        ipv4_address: 10.0.1.3 # Using .3 for HostA

  hb: # Host B
    build: .
    hostname: hostb
    stdin_open: true
    tty: true
    cap_add:
      - ALL
    privileged: true
    networks:
      net_r3_hb:
        ipv4_address: 10.0.6.3 # Using .3 for HostB

  r1: # Router 1
    build: .
    hostname: r1
    stdin_open: true
    tty: true
    cap_add:
      - ALL
    privileged: true
    networks:
      net_ha_r1: # Link to HA
        ipv4_address: 10.0.1.4 # Using .4 for R1
      net_r1_r2: # Link to R2
        ipv4_address: 10.0.2.4 # Using .4 for R1
      net_r1_r4: # Link to R4
        ipv4_address: 10.0.3.4 # Using .4 for R1

  r2: # Router 2
    build: .
    hostname: r2
    stdin_open: true
    tty: true
    cap_add:
      - ALL
    privileged: true
    networks:
      net_r1_r2: # Link to R1
        ipv4_address: 10.0.2.5 # Using .5 for R2
      net_r2_r3: # Link to R3
        ipv4_address: 10.0.4.5 # Using .5 for R2

  r3: # Router 3
    build: .
    hostname: r3
    stdin_open: true
    tty: true
    cap_add:
      - ALL
    privileged: true
    networks:
      net_r2_r3: # Link to R2
        ipv4_address: 10.0.4.4 # Using .4 for R3
      net_r4_r3: # Link to R4
        ipv4_address: 10.0.5.4 # Using .4 for R3
      net_r3_hb: # Link to HB
        ipv4_address: 10.0.6.4 # Using .4 for R3

  r4: # Router 4
    build: .
    hostname: r4
    stdin_open: true
    tty: true
    cap_add:
      - ALL
    privileged: true
    networks:
      net_r1_r4: # Link to R1
        ipv4_address: 10.0.3.5 # Using .5 for R4
      net_r4_r3: # Link to R3
        ipv4_address: 10.0.5.5 # Using .5 for R4

# Define the networks (corresponding to the links in the diagram)
networks:
  net_ha_r1: # Network between HA and R1
    driver: bridge # Default Docker network driver
    ipam: # IP Address Management
      driver: default
      config:
        - subnet: 10.0.1.0/24
  net_r1_r2: # Network between R1 and R2
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.2.0/24
  net_r1_r4: # Network between R1 and R4
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.3.0/24
  net_r2_r3: # Network between R2 and R3
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.4.0/24
  net_r4_r3: # Network between R4 and R3
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.5.0/24
  net_r3_hb: # Network between R3 and HB
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.6.0/24
